"""Update user account models

Revision ID: 3ccb04462077
Revises: 
Create Date: 2026-07-24 15:24:14.529992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ccb04462077'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('available_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('freeze_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('freeze_reason')
        batch_op.drop_column('available_balance')
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('status')
        batch_op.drop_column('address')
        batch_op.drop_column('country')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
