"""Added related account

Revision ID: 66d7a2c2dc65
Revises: 6dd98849b0a1
Create Date: 2026-07-25 15:24:55.653757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d7a2c2dc65'
down_revision = '6dd98849b0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_account', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('related_account')

    # ### end Alembic commands ###
