"""Remove unique transaction reference

Revision ID: 88f7a710737e
Revises: 66d7a2c2dc65
Create Date: 2026-07-25 22:38:49.608002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f7a710737e'
down_revision = '66d7a2c2dc65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_transaction_reference'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_transaction_reference'), ['transaction_reference'])

    # ### end Alembic commands ###
